[tool.poetry]
name = "talentsync"
version = "0.1.0"
description = ""
authors = ["Priscilla Santos <priscilla.batista18@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
